### ISSUE TITLE
Add tip: wrapper utility

### ISSUE THREAD

**Issue by tomjbradley** [AllThingsSmitty/css-protips#135]
You should add a tip for a simple wrapper/container utility. For example:
```css
.wrapper {
  margin-right: auto;
  margin-left:  auto;
  max-width: 960px;
  padding-right: 10px;
  padding-left:  10px;
}
```
It's explained more in [this css-tricks article](https://css-tricks.com/best-way-implement-wrapper-css/).

I'd be happy to add it if you want.
