### ISSUE TITLE
Max Function for Max-Width

### ISSUE THREAD

**Issue by shayanfpg9** [AllThingsSmitty/css-protips#158]
Hi, I had a request,
can I add ```max``` function to this repository?

```css 
div {
    max-width: max(50vw, 300px);
}
```

to show if document width less than 300px the max width of div be 300px else the max width of div will be 50vw.

Thank you
