### ISSUE TITLE
How do I overlay an image over the background one ?

### ISSUE THREAD

**Issue by mohakexe** [AllThingsSmitty/css-protips#167]

**Comment by NarpatAanjana** [comment]
You can use a <div> element for this purpose.
and following CSS
.container {
  background-image: url('background-image.jpg');
  position: relative;
}

.overlay {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1;
}

**Comment by MegRCooper** [comment]
Hi, I've created a Word doc with a few different examples of an overlay with CSS.
[Quick Overview (CSS Overlay).docx](https://github.com/AllThingsSmitty/css-protips/files/11435386/Quick.Overview.CSS.Overlay.docx)

**Comment by DonMiller9294** [comment]
You can overlay an image over a background using CSS by using the `position` property and the `::before` or `::after` pseudo-elements. Here's a basic example:

HTML:
```html
<div class="container">
  <img src="overlay-image.jpg" alt="Overlay Image">
  <p>Content goes here</p>
</div>
```

CSS:
```css
.container {
  position: relative;
}

.container::before {
  content: "";
  background: url('background-image.jpg');
  background-size: cover;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0.5; /* Adjust the opacity as needed */
  z-index: -1; /* Place the overlay behind the content */
}
```

In this example, the `::before` pseudo-element is used to create the overlay. Adjust the `background` property with the path to your background image, and you can also adjust the `opacity` to control the overlay's transparency.

Make sure to adjust the paths to your actual image files, and customize the styles to match your design.

**Comment by happy315** [comment]
# The HTML will look like this: 



```html
 <header>
        <section class='hero-header'>
            <h1>Software development</h1>
            <h2>Javascript developer</h2>
            <button>Hire Me</button>
        </section>
    </header>


```
# The css will look like this 

```css

 header {
        height: 100vh;
        width: 100%;
        text-align: center;
        padding-top: 100px;
        color: white;
        overflow: hidden;
        background: #c04848; /* fallback for old browsers */
        background: linear-gradient(rgb(72, 0, 72, 0.8), rgb(192, 72, 72, 0.8)),
          url("/luke-peters-B6JINerWMz0-unsplash.jpg");
        background-size: cover;
        background-repeat: no-repeat;
      }
      header h1,
      h2 {
        margin: 2rem;
        font-size: 3rem;
      }
      header button {
        padding: 1.5rem;
        border-radius: 0.2rem;
        background-color: white;
        border: none;
        font-size: 1.5rem;
        color: rgb(72, 0, 72, 0.8);
        font-weight: bold;
      }
```
# The result will look like this
![Screenshot 2023-09-25 at 11 00 30 PM](https://github.com/AllThingsSmitty/css-protips/assets/94611400/be397c43-27d6-4ec7-a58f-4a724e95236a)
