### ISSUE TITLE
Alternative for Apply/Unapply Borders

### ISSUE THREAD

**Issue by ImBobby** [AllThingsSmitty/css-protips#2]
I personally use this technique in professional projects
```CSS
.nav li + li {
  border-right: 1px solid #666;
}
```
this technique has less specificity and support IE7. Thought?
