### ISSUE TITLE
negative margins

### ISSUE THREAD

**Issue by marcobiedermann** [AllThingsSmitty/css-protips#30]
using negative `margin`s to get rid of `:first-child` and `:last-child` selector

instead of this

```
.navigation li {
  display: inline-block;
  margin: 0 .5rem;
}

.navigation li:first-child {
  margin-left: 0;
}

.navigation li:last-child {
  margin-right: 0;
}
```

you could write

```
.navigation {
  margin: 0 -.5rem;
}

.navigation li {
  display: inline-block;
  margin: 0 .5rem;
}
```

It is similar to the `flexbox` `space-betweet` technique but `flexbox` does not work in every situation.

If you agree with me, I could send you a PR :)

**Comment by neworldexport** [comment]
Congrat

**Comment by vikrantnegi** [comment]
Nice.

**Comment by alexcarpenter** [comment]
or you could simplify it to be:

```
.navigation {
  display: flex;
}

.navigation li:not(:first-of-type) {
  margin-right: 1rem;
}
```

**Comment by marcobiedermann** [comment]
@alexcarpenter 
This is not the same:

Your example might work items which are only placed in a row.
It does not work with a grid like layout (rows & cols).
With negative margins you can cut of the gutter on all edges (top, right, bottom, left).
Great for a multi line image gallery or products page

**Comment by edmundojr** [comment]
Good tip! With flexbox we could do this as well:

```css
.nav {
  display: flex;
  justify-content: space-between;
}

.nav li {
  /* Nothing needed here */
}
```

Cheers.

**Comment by edmundojr** [comment]
I think we could also use the [adjacent selector](https://css-tricks.com/almanac/selectors/a/adjacent-sibling/) – that's what I end up doing in most cases:

```css
.navigation li + li {
  display: inline-block;
  margin-left: 1rem;
}
```

Supported in every browser too!

**Comment by marcobiedermann** [comment]
@edmundojr As mentioned this only would work in one direction. Horizontally or vertically.

Using negative `margins` will solve the problem with space between all items equally. No matter which direction (inline or stacked).

**Comment by marcobiedermann** [comment]
Maybe this example will clear some things up: https://jsfiddle.net/m412c0/yjL5qf0b/1/

```html
<div class="outline">
  <ul class="items">
    <li class="item"></li>
    <li class="item"></li>
    <li class="item"></li>
    <li class="item"></li>
    <li class="item"></li>
    <li class="item"></li>
    <li class="item"></li>
    <li class="item"></li>
    <li class="item"></li>
  </ul>
</div>
```

```css
.outline {
  border: 1px solid blue;
}

.items {
  display: flex;
  flex-wrap: wrap; 
  list-style: none;
  margin: -0.5rem;
  overflow: hidden;
  padding: 0;
}

.item {
  background-color: tomato;
  flex-basis: calc(33.33% - 1rem);
  margin: 0.5rem;
  min-height: calc(100vw / 3 - 1rem);
}
```

![image](https://cloud.githubusercontent.com/assets/5244986/20578948/32250968-b1ca-11e6-8de8-ed6cab4daed7.png)
