### ISSUE TITLE
Issues with `line-height`

### ISSUE THREAD

**Issue by thierryk** [AllThingsSmitty/css-protips#44]
**`line-height` to `body`**

``` css
body {
  line-height: 1;
}
```

The above value is too small and will create problems with descenders/ascenders. I think it'd be better to use a more realistic one (i.e. `1.5`) so people who copy/paste won't find out the hard way.

**Use `:root` for Flexible Type**

It is better to use unit-less values with `line-height` because the way inheritance works with this property (what is inherited is a _computed value_).

So I'd suggest to use:

``` css
body {
  font: 1em/1.6rem sans-serif;
}
```

**Comment by AllThingsSmitty** [comment]
@thierryk for the flexible type tip, do you mean:

```css
body {
  font: 1em/1.6 sans-serif;
}
```

Removing the unit from the line-height as you suggest.
