### ISSUE TITLE
'Style "Default" Links' is not a pro tip

### ISSUE THREAD

**Issue by fabsn182** [AllThingsSmitty/css-protips#45]
You suggest to use `a[href]:not([class])` for a-Tags without an `href`-attribute. But why?
`a` is everything you need to style for this case. Heck, you can use `a:link, a:visited` if that floats your boat but adding two different type of selectors ([attribute], :not()) is in no way a pro tip.

**Comment by sentience** [comment]
`a` (and `a:link, a:visited`) matches all links, whether they have a `class` attribute or not.

`a[href]:not([class])` matches *only* links with *no* `class` attribute. This is preferable because you can assign specific styles for those “ordinary” links without having to then override those styles to remove them from your “specialized” (`class`ed) link styles.

For example, if you wanted your `class`-less links to be bold, but your `class`ed links to be normal, you could write:

```css
a { font-weight: bold; }
a.someclass { font-weight: normal; }
a.anotherclass { font-weight: normal; }
a.thirclass { font-weight: normal; }
```

…or you could just write this one rule:

```css
a[href]:not([class]) { font-weight: bold; }
```
