### ISSUE TITLE
Add Attribute Selectors

### ISSUE THREAD

**Issue by Electrofenster** [AllThingsSmitty/css-protips#5]
You can use attribute selectors to display the link when the a-tag is empty but the href-tag is an link.

Example:
html:
```html
<a href="http://google.de"></a>
<a href=""></a>
<a href="http://bing.com">Test 1</a>
<a href="#">Test2</a>
```
css:
```css
a[href^=http]:empty::before {
    content: attr(href);
}
```

**Comment by AllThingsSmitty** [comment]
@Electrofenster that's a good one, Lars. Thanks for suggesting it.

**Comment by AllThingsSmitty** [comment]
Added with https://github.com/AllThingsSmitty/css-protips/commit/43e82e58e7649c0d233250fe04b59f26fd2918ba.

**Comment by Electrofenster** [comment]
thanks :+1:

**Comment by Electrofenster** [comment]
@AllThingsSmitty maybe you can add these for input's too:

```css
input[type="submit"] {
	border: 1px solid #EFEFEF;
}

input[type="text"] {
	border: 1px solid #CCCCCC;
}

input[type="password"] {
	border: 1px solid #FF0000;
}
```
