### ISSUE TITLE
Nice alternative for text-decoration: underline

### ISSUE THREAD

**Issue by pugsiman** [AllThingsSmitty/css-protips#9]
A good looking alternative I found for `text-decoration: underline;` is using border-bottom instead, it gives you more control over the way it looks.
For example: `border-bottom: 1px solid black;` or:
http://codepen.io/pugsiman/pen/vNKBPe

**Comment by robsonsobral** [comment]
But it isn't always the best solution. E.g., the specification for `abbr` changed from using `border-block-end: dotted 1px` to `text-decoration: dotted underline`, which isn't support on all browsers yet.

From the [default styles](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3):

```css
abbr[title], acronym[title] { text-decoration: dotted underline; }
ins, u { text-decoration: underline; }
del, s, strike { text-decoration: line-through; }
blink { text-decoration: blink; }
```

This changed because of issues with the japanese Windows typeface, Meyro:

![screenshot of some underlined words using the Meyro typeface](https://bug1157076.bmoattachments.org/attachment.cgi?id=8595714)

My suggestion is to use both and `@supports (text-decoration: dotted underline)`.
